### PR TITLE
Update Media.php to extend try catch block

### PR DESCRIPTION
**Pull request by parekhreena**
Fix for issue-189, fixing error when saving blog or freeshipping bar without an image.

### CODE REVIEW

**Comment by gixid192** [comment]
Thanks for your pull request, we already released a new version of Blog extension and it does not require module Core to be updated.
If you have further comments/suggestions, please feel free to reopen this.

**Comment by parekhreena** [comment]
Please read the commit message properly before closing the PR, the error was not just happening in blog module, this error happens in every module of yours which uses the file uploader. We are facing this error in Mageplaza free shipping bar extension for magento2 which is calling this module's Media file and throwing an exception. Adding the fix to your core module will help avoid application of a dirty quick-fix patch in projects of your clients.

**Comment by gixid192** [comment]
My bad! So sorry for that.

If you don't mind, want to discuss the issue a little bit. Do you think that we should update the Core module instead of fixing the current module itself?
I mean, I understand that it will be one-for-all if we deploy the fix in the Core module, however, the actual problem is in the module itself.

I checked the Blog extension, the fix is: no image -> don't upload.
Hasn't checked the shipping bar extension yet. But do you think that the problem lines in the module itself?

**Comment by parekhreena** [comment]
Yes, you should fix the core module. Free shipping bar extension provides a backend interface to add details of the free shipping bar, when the image field is left empty, it should be using the color, because image field is optional. In this testcase when we try to save the shipping bar it throws an exception saying no file was uploaded. This exception comes from the core module. If the image file is not there, simply skip the field, why throw an exception ?

**Comment by gixid192** [comment]
I'm thinking in a different way.
Here is what I see from the Free Shipping Bar extension:
- When you press Save, it calls the `prepareData`
- In prepareData, it calls the Upload image function (from Core) immediately.

So my thought is: In the prepareData, skip the Upload function when there's no image at all.
This is what I've been thinking, the issue is in the module itself, not Core.

Could you let me know your opinion about this?

**Comment by parekhreena** [comment]
@gixid192 You applied a similar approach with your blog module and how did that work out ? Worked for 1 extension and rest are still broken (free shipping bar for instance). The decision is yours, you can either release an update for your 10 different extensions or patch your 1 core module so that it does not break 10 different extensions.

**Comment by gixid192** [comment]
I totally agree with you! If we follow this path, we will need to fix each and every module.
I just want to see how you see the problem, thanks for your time!

We will check and merge the code soon.

**Comment by parekhreena** [comment]
@gixid192 Ok, please do it ASAP as this is a blocker for my project.

**Pull request merged**
