### PR TITLE
Fix: Deprecated Functionality: Creation of dynamic property 

### PR DESCRIPTION
**Pull request by MoemenDarwish**
Fix: Deprecated Functionality: Creation of dynamic property in GetUpate::$notifierPool

Magento 2.4.6
PHP 8.2

SCR-20230604-lo6

### CODE REVIEW

**Comment by hostep** [comment]
We run into this as well with PHP 8.2 during cronjob runs.

@haitv282 or @chuccv: can this get merged and can you tag a new version?

Thanks!

**Comment by chuccv** [comment]
fix(Cron):  var:$notifierPool

**Comment by hostep** [comment]
Thanks for the quick merge!

Any idea when a new version will be released that will include this fix?
Thanks again!

**Comment by hostep** [comment]
Looks like this is now included in version 1.5.5: https://github.com/mageplaza/module-core/compare/v1.5.4...v1.5.5

Thanks again @chuccv!

**Pull request merged**
